# Generated by Django 2.2.14 on 2022-10-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='bought',
            field=models.IntegerField(default=0),
        ),
    ]
