# Generated by Django 2.2.14 on 2022-10-02 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20221002_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='started_date',
        ),
    ]
