# Generated by Django 2.2.14 on 2022-10-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='ended_date',
        ),
        migrations.AddField(
            model_name='projects',
            name='time_left',
            field=models.CharField(default='2022-10-03 08:34:42.358221', max_length=50),
        ),
    ]
