# Generated by Django 2.2.14 on 2022-10-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221002_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/example.jpg', upload_to='user\\'),
        ),
    ]
